name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2

      - name: Install dependencies
        shell: bash
        run: bun install --frozen-lockfile

      - name: Create Release Pull Request
        uses: tepzilon/changesets-action@23c046d21c2c3818e7d39eee3c9377ad6a7493e9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}